### ISSUE TITLE
fir.im无法显示Change log

### ISSUE THREAD

**Issue by leezhm** [FIRHQ/flow.ci#104]
我想将git的commit信息自动同步到fir.im的changelog中去，根据官方提示，步骤如下：

1、在工作流git clone之后，创建自定义脚本，脚本内容如下：
```
echo "获取git log"
CHANGE_LOG=$(git log --pretty=format:"%s" -1 $describe)
echo $CHANGE_LOG
```
2、在fir.im的上传插件中设置$FIR_CHANGELOG为`$CHANGE_LOG`

构建过程，可以正常获取commit信息，但是在上传到fir.im后，Changelog显示如下：
```
Changelog

2017-01-03:16:09:59: build from flow.ci
```

请问官方的同学，这个过程是否正确？

**Comment by capegf** [comment]
改成 export CHANGE_LOG=$(git log --pretty=format:"%s" -1 $describe)

**Comment by leezhm** [comment]
谢谢@capegf 同学，已经可以了！
