### ISSUE TITLE
尚未支持Coding.Net

### ISSUE THREAD

**Issue by lijy91** [FIRHQ/flow.ci#11]

**Comment by trawor** [comment]
https://open.coding.net/oauth.html

**Comment by yunheli** [comment]
@lijy91 已经支持了

**Comment by lijy91** [comment]
@yunheli 目前看来只能支持本人创建的项目，非本人创建的项目就算有管理员权限也无法使用。

**Comment by jicheng1014** [comment]
@lijy91   Hello  Coding.net 官方提供的API 要求是本人项目[（详细情况）](https://open.coding.net/oauth.html#oauth-2-251-webhook
)，我们正跟coding沟通看看能否新开接口

```
```

**Comment by trawor** [comment]
针对这个 重新开了个 issue， ref #51
