### ISSUE TITLE
删除应用报错

### ISSUE THREAD

**Issue by CandyLikeSmile** [FIRHQ/flow.ci#15]
<img src="https://dn-shimo-image.qbox.me/kWmjOCBsA1MOmA0i.png!thumbnail" width=680>

报错信息如图：
vendor.91cc6ef….js:18 DELETE http://api.flow.ci/projects/56f8c7089b79b2385c00009e e.exports @ vendor.91cc6ef….js:18(anonymous function) @ vendor.91cc6ef….js:24e.exports @ vendor.91cc6ef….js:24
settings:1 XMLHttpRequest cannot load http://api.flow.ci/projects/56f8c7089b79b2385c00009e. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dashboard.flow.ci' is therefore not allowed access. The response had HTTP status code 404.
app.b6c0f07b3b3ea1df05bc.js:19 Action type is undefined undefined

**Comment by NaixSpirit** [comment]
api 是开了跨域的, 我这里没复现

**Comment by trawor** [comment]
可能是当时服务器故障导致 先关了 有问题再打开
