### ISSUE TITLE
是否可以有再跑一次测试的功能

### ISSUE THREAD

**Issue by qingfeng** [FIRHQ/flow.ci#19]
![image](https://cloud.githubusercontent.com/assets/18495/14452158/4a251c18-00bf-11e6-8fef-69a5d340d89a.png)
比如这个环境失败了，但可能是偶发，能否手动触发一次重跑？

**Comment by trawor** [comment]
功能已经有了  UI上还没表现出来~~

**Comment by qingfeng** [comment]
赞👍，期待
