### ISSUE TITLE
flow.ci 没有获取status权限？

### ISSUE THREAD

**Issue by trawor** [FIRHQ/flow.ci#20]
把CI结果反馈给github需要用户的status权限

**Comment by trawor** [comment]
see also https://github.com/FIRHQ/flow.ci/issues/18#issuecomment-208724057

**Comment by qingfeng** [comment]
另外， 好像授权了这个权限，也没有回写回去，还挺奇怪的

**Comment by trawor** [comment]
是的 这个可能有bug 已经assign给同事去处理了

**Comment by qingfeng** [comment]
重新获得授权这个求提高优先级。。。

**Comment by JuoCode** [comment]
@qingfeng 已有解决方案，稍后联系

**Comment by qingfeng** [comment]
Cool，期待～
