### ISSUE TITLE
跑测试的时候，获取的Git仓库地址不正确

### ISSUE THREAD

**Issue by qingfeng** [FIRHQ/flow.ci#21]
PR的发起未必是当前仓库，可能是开发者自己fork出去的仓库，所以git clone的地址应当是开发者本身的仓库+branch，但是目前默认的是从主仓库去clone代码，应当从PR由谁发来的那个仓库来获取代码

![image](https://cloud.githubusercontent.com/assets/18495/14456190/3ce8671e-00d6-11e6-8349-2bd2da4ea83e.png)

**Comment by NaixSpirit** [comment]
正在修改

**Comment by NaixSpirit** [comment]
目前 flow.ci 里面单个项目对应 ssh 密钥是没法拉去其他仓库的代码的, 需要其他仓库的开发者手动添加该项目的公钥

**Comment by yunheli** [comment]
@qingfeng  您好，对您造成的不便敬请谅解

```
	PR跨项目操作的问题已经解决，但是需要你的配合
	PR跨项目操作时需要对另一个项目有 git 权限，分两种情况
		1、公开项目则好说,不需要对项目添加 deploy_key ,直接 clone 代码
		2、私有项目需要把 deploy_key 添加到项目中，然而 github 中相同的 deploy_key
	不能放在多个项目中，所以需要你的小小配合一下，把 deploy_key 在项目中删除添加到
	user 的 SSH KEY 中暂时只能这样实现跨项目PR,我们也正在努力寻找更加方便的方法解
    决这个问题，对您造成的不便敬请谅解
```

**Comment by qingfeng** [comment]
明白了，收到

**Comment by qingfeng** [comment]
今天尝试弄了一下，但这样有个问题，多个user协作的时候没法弄阿。。。让用户自己分别去授权一下，分别一个key不行吗？

**Comment by yunheli** [comment]
@qingfeng 现在 pr 关联的两个项目都在 flow.ci 上面创建了，就会有权限去 clone 两个项目的代码了

**Comment by qingfeng** [comment]
👌的！我试试

**Comment by qingfeng** [comment]
感谢！新增加的fork仓库，如何增加clone权限？

**Comment by yunheli** [comment]
@qingfeng 只需要把新添加的fork仓库在flow.ci上创建即可有clone的权限了
