### ISSUE TITLE
好像现在不能创建测试了？

### ISSUE THREAD

**Issue by qingfeng** [FIRHQ/flow.ci#38]
一创建就报未知错误
![image](https://cloud.githubusercontent.com/assets/18495/14982154/f2bded16-1166-11e6-899f-2687cb54e7a5.png)

**Comment by qingfeng** [comment]
现在又好了，刚才有3个测试连续创建失败了，具体可以看 http://dashboard.flow.ci/projects/56f4d9e29b79b27c8f00000b/builds/57288e1b9b79b24117000023

**Comment by JuoCode** [comment]
创建“测试”？

**Comment by JuoCode** [comment]
我明白了，是手动 Build 功能，我们检查一下

**Comment by NaixSpirit** [comment]
docker 磁盘满了, fixed
