### ISSUE TITLE
测试邮件发送略慢

### ISSUE THREAD

**Issue by qingfeng** [FIRHQ/flow.ci#39]
能否直接接入Slack?或者提供一个webhook也可以～

**Comment by qingfeng** [comment]
而且，好像不是每次都会发送邮件，例如这次测试跑完就没有发邮件 http://dashboard.flow.ci/projects/56f4d9e29b79b27c8f00000b/builds/57288e849b79b24add000000

**Comment by JuoCode** [comment]
@qingfeng 
1. Webhook 已经在计划中，到时候可以直接将 build 结果发送到 slack
2. 现在已经有发送到 slack 的插件了，你可以在 flow 中添加（如果前面的 step 失败以后，发送 slack 的 step 就不会走了）
3. 没有发送邮件的情况我们再检查一下

**Comment by qingfeng** [comment]
COOL，另外，好像测试通过并不会发邮件？只是失败才发

**Comment by trawor** [comment]
嗯 这个目前是默认这么处理的, 因为还没有界面让用户设置  有界面了就可以自由设置了

QingFeng <notifications@github.com>于2016年5月4日周三 上午10:31写道：

> COOL，另外，好像测试通过并不会发邮件？只是失败才发
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/FIRHQ/flow.ci/issues/39#issuecomment-216726067>
>
-- 

--
T.W
