### ISSUE TITLE
Slack没有正确发送信息

### ISSUE THREAD

**Issue by qingfeng** [FIRHQ/flow.ci#40]
显示执行成功的绿色，但是实际没有执行成功，而且不知具体的报错信息，粘了一下截图
![image](https://cloud.githubusercontent.com/assets/18495/15011374/06f4627a-1224-11e6-867a-903784b6900a.png)

**Comment by jicheng1014** [comment]
Hello 清风，slack插件在我们设计时为了满足更高的定制型， `$FLOW_SLACK_MSG_JSON` 需要符合 `slack` 要求的 json 格式。

如
```
{"text": "这里填写"}
```

只不过我们以后会在前端提供两种模式，常规模式 和 高阶模式, 常规模式直接输入字符串即可  👯

**Comment by qingfeng** [comment]
原来如此，小建议：界面给个提示，不然真不知道。。。另外，如果是失败了建议还是返回红色，不然会以为是成功了

**Comment by trawor** [comment]
界面还是要大改的 :) @qingfeng
