### ISSUE TITLE
关于pep8插件

### ISSUE THREAD

**Issue by qingfeng** [FIRHQ/flow.ci#41]
![image](https://cloud.githubusercontent.com/assets/18495/15038856/39bc09ae-12da-11e6-9d93-4d22e5488075.png)
面对这个输入框不知道要输入什么。。。

能否约定一个配置文件，去读取配置好的pep8的配置？

```
[flake8]
ignore = W293, W291, F403
max-line-length = 160
exclude = ogow/libs/*
max-complexity = 10
```

以上

**Comment by qingfeng** [comment]
另外，看了一下log，我看装的是pep8，能否让用户自定义安装flake8?

```
Collecting pep8
  Downloading pep8-1.7.0-py2.py3-none-any.whl (41kB)
Installing collected packages: pep8
Successfully installed pep8-1.7.0
You are using pip version 7.1.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
CHECK FILE COUNT 1794
CHECK WARN COUNT 151
```

**Comment by JuoCode** [comment]
@qingfeng 
> 面对这个输入框不知道要输入什么。。。

这个是一个 BUG，我们会把一些插件的源码显示出来，用户可以进行编辑

**Comment by JuoCode** [comment]
> ...能否让用户自定义安装flake8?

我们先调研一下，非常感谢您的反馈 👍

**Comment by VeryCB** [comment]
flake8 +1

**Comment by trawor** [comment]
@VeryCB 现在可以先用个替代的办法： 我们开放了系统权限 所以可以任意的安装，在初始化的那个插件中，添加脚本安装`pip install`或者`sudo apt-get install`

稍后我们会添加到默认的环境中
