### ISSUE TITLE
Regular match好像不匹配tag?

### ISSUE THREAD

**Issue by qingfeng** [FIRHQ/flow.ci#44]
尤其是移动端的开发，在准备打包的时候打一个tag应该还是比较常见的，期望Regular match也可以读取tags，进行编译打包

![image](https://cloud.githubusercontent.com/assets/18495/15136562/1fa197e4-16b5-11e6-9090-225d92e9fe75.png)

**Comment by trawor** [comment]
这个可以有 要放到下个milestone了  :)
