### ISSUE TITLE
android 初始化 input似乎出问题了

### ISSUE THREAD

**Issue by PaperHS** [FIRHQ/flow.ci#49]
flow_cmd "echo $FLOW_PROJECT_ANDROID_SDK" --echo

output:
$ echo 
$ echo 
$ chjava jdk8
$ java -Xmx32m -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_65
Error: Oops, it looks like you didn't provide an argument for '-t'.
'--abi' was found instead.

**Comment by yunheli** [comment]
@PaperHS 非常感谢您给提的bug,已经解决并且已经上线，对您造成的不便敬请谅解
