### ISSUE TITLE
fir upload 插件报错

### ISSUE THREAD

**Issue by PaperHS** [FIRHQ/flow.ci#50]
Warning! PATH is not properly set up, '/home/flow/.rvm/gems/ruby-2.2.2/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.2'.
Using /home/flow/.rvm/gems/ruby-2.2.2

**Comment by yunheli** [comment]
@PaperHS 这个bug已经解决，你把fir uploader插件删除之后再重新添加一次就可以了，对您造成的不便敬请谅解
