### ISSUE TITLE
Coding push 操作不能触发 build

### ISSUE THREAD

**Issue by twiceyuan** [FIRHQ/flow.ci#53]

**Comment by trawor** [comment]
感谢反馈 这个已经修复

**Comment by twiceyuan** [comment]
@trawor 你好，我这儿还是不可以，Coding 上需要设置 hook 吗，没看到文档里有说明

**Comment by jicheng1014** [comment]
@twiceyuan  hello， 我们分析了下日志，是webhook 添加失败导致的   您可以在项目设置里拿到webhook, 填写到coding.net 项目里    或者如果觉得麻烦，可以在flow.ci 里删除这个项目重新添加
