### ISSUE TITLE
gitlab 部分项目提示没权限 实际有权限

### ISSUE THREAD

**Issue by shwhl** [FIRHQ/flow.ci#54]

**Comment by jicheng1014** [comment]
Hello， Gitlab 使用的是  `Private Token` 授权， 这个权限是最大值的。 能详细的说一下您遇到的情况以及项目状态，从属么？ thx

**Comment by shwhl** [comment]
本人是group的owner权限，所有项目都是最大权限， 我们有十几个项目，但是有一部分显示在没权限列表里，部分没权限的项目还是我有过commit的

**Comment by jicheng1014** [comment]
不知道您说的是不是在pull request 当中 git 拉代码的时候出现的？  我们flow.ci  在这次版本当中暂时不支持跨项目的pull_request，如果您想临时用一下的话，可以将项目的公钥设置为您gitlab账户的公钥。

跨项目的pr 将在下一版本中实现。

如果还有疑问，欢迎到gitter https://gitter.im/FIRHQ/flow.ci 中与我们取得联系

**Comment by shwhl** [comment]
不跨项目

**Comment by shwhl** [comment]
这个issue是关于项目没权限的，PR问题回复到#55里，不然容易搞混，thx

**Comment by jicheng1014** [comment]
您能给出更多的不能拉取项目的细节么？我们这边测试目前来看都能开，所以可能需要您这边更多的信息
 比如是稳定的没有权限  还是 有时候有权限，有时候没权限？
您是私有部署的 gitlab，如是，是第几版的gitlab? 还是直接使用的gitlab.com 的服务? 

您可以在https://gitter.im/FIRHQ/flow.ci 当中与我们去的实时联系，thx

**Comment by wanghanlin** [comment]
fixed
