### ISSUE TITLE
gitlab merge request 提示没权限

### ISSUE THREAD

**Issue by shwhl** [FIRHQ/flow.ci#55]
没权限拉取 pr 的关联项目， 请确保 pr 的关联项目在 flow.ci 已经创建项目

**Comment by shwhl** [comment]
PR是项目的一个branch， 项目在group下，其他关系见#54

**Comment by jicheng1014** [comment]
您好   coding 的 PR  是跨项目的PR   我们目前暂时不支持跨项目的，更详细的描述请参考 https://github.com/FIRHQ/flow.ci/issues/54

**Comment by shwhl** [comment]
gitlab, not coding

**Comment by jicheng1014** [comment]
@shwhl    您好， 我们现在暂时不支持跨项目的 PR，如果您急需使用，可以采取我在 #54 中的方式来曲线救国， 我们将会在下一版本中支持跨项目的PR 
如需更一步支持，请通过 https://gitter.im/FIRHQ/flow.ci 联系我们

**Comment by shwhl** [comment]
先close了，有问题我在reopen
