### ISSUE TITLE
好像现在CI卡住了？

### ISSUE THREAD

**Issue by qingfeng** [FIRHQ/flow.ci#58]
卡住好久不动了，后续新创建的jobs都不动了
![image](https://cloud.githubusercontent.com/assets/18495/16299144/5791eb4e-396b-11e6-8169-abe903ae05fb.png)

**Comment by trawor** [comment]
队列问题，已经修复了

**Comment by manajay** [comment]
可是我的还是卡死啊
![qq20161223-124025](https://cloud.githubusercontent.com/assets/13750333/21447249/02b68a8a-c90d-11e6-93d4-a01d89e8dd5f.png)
