### ISSUE TITLE
请问有计划支持oc或者swift吗?

### ISSUE THREAD

**Issue by devjia** [FIRHQ/flow.ci#59]
一直在关注flow.ci的进展,也想大概了解下对于iOS的支持情况.

**Comment by trawor** [comment]
感谢关注。当天马上就回了邮件 好像这里没显示。。。
关于iOS，我们内部已经在用了，目前主要是大规模OSX使用，在找合适的云服务商，预计2个月后上线

**Comment by devjia** [comment]
你好,可以给个邀请码么,没收到邮件...

**Comment by trawor** [comment]
@devjia 邀请码最近发了一大批 收到了吗?

**Comment by trawor** [comment]
![2016-11-03 11 03 54](https://cloud.githubusercontent.com/assets/72015/19954687/42408fb8-a1b5-11e6-89cb-733ec9d5c85d.png)

btw, 我们会直接支持Xcode Bot 🎱

**Comment by devjia** [comment]
@trawor 感谢您的回复. 现在好像是开放注册了,已经注册成功,但是没有找到iOS构建模板呢.
难道是直接使用Xcode server的bot吗......

**Comment by trawor** [comment]
@devjia iOS已经可以用 但是xcode bot还在测试中
