### ISSUE TITLE
Android编译失败，找不到SDK文件夹

### ISSUE THREAD

**Issue by rorschach** [FIRHQ/flow.ci#60]
> FAILURE: Build failed with an exception.
> - What went wrong:
>   A problem occurred configuring project ':app'.
>   
>   > The SDK directory '/opt/Sdk' does not exist.
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 1 mins 22.643 secs
> 
> The command failed and exited with 1.
> 
> Your build has been stopped.

**Comment by rorschach** [comment]
Initialize & Build 均使用默认配置，到今天为止仍然不能编译成功

**Comment by capegf** [comment]
@rorschach 你需要把本地的local.properties在.gitignore里添加下，如果你放到项目里，会导致找不到sdk目录

**Comment by rorschach** [comment]
去掉local.properties文件后，报以下错误

> $ ./gradlew clean
> Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: /home/flow/.gradle/wrapper/dists/gradle-2.10-all/5b6kqrscumh9p4evkkemdk57ad/gradle-2.10-all.zip.lck (Disk quota exceeded)
>     at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
>     at org.gradle.wrapper.Install.createDist(Install.java:47)
>     at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
>     at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
> Caused by: java.io.FileNotFoundException: /home/flow/.gradle/wrapper/dists/gradle-2.10-all/5b6kqrscumh9p4evkkemdk57ad/gradle-2.10-all.zip.lck (Disk quota exceeded)
>     at java.io.RandomAccessFile.open0(Native Method)
>     at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
>     at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
>     at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:49)
>     ... 3 more

The command failed and exited with 1.

Your build has been stopped.
