### ISSUE TITLE
通知邮箱能否增加多个?

### ISSUE THREAD

**Issue by foolchen** [FIRHQ/flow.ci#64]
通知邮箱能否增加多个?
因为我正在维护的项目不止一个,而且属于不同的团队,邮箱也不同
现在所有的通知都只会发送到同一个邮箱,有时挺不方便的
所以,在将来的更新中,能否针对project设定不同的通知邮箱?

**Comment by trawor** [comment]
肯定会的，已经在开发计划里

**Comment by trawor** [comment]
你好，请在`Email Sender`插件中，直接用`,`分割收件人就可以了

![2016-08-23 11 28 49](https://cloud.githubusercontent.com/assets/72015/17879482/e22ab8ce-6924-11e6-85f7-dccef726e245.png)

ps, 现在默认的通知系统还没有开放出来供自定义配置，所以`Email Sender`是个折衷的临时方案
