### ISSUE TITLE
Bitbucket authorisation is failing

### ISSUE THREAD

**Issue by petercsoka** [FIRHQ/flow.ci#66]
Currently I'm getting error messages about Bitbucket authorisation failure. Tried to find a way to disconnect and reconnect it from my account but no luck.
Screenshot:
<img width="803" alt="screen shot 2016-10-13 at 11 43 28" src="https://cloud.githubusercontent.com/assets/284333/19346245/5ccbf0c4-913a-11e6-9dbb-f83db8e9bed4.png">

**Comment by trawor** [comment]
Thanks, we had this bug in list. The bitbucket token expired  but we don't
give a reconnect way. Will fix this later.

Peter Csoka notifications@github.com于2016年10月13日星期四 18:44写道：
