### ISSUE TITLE
什么时候NODE支持 v6？

### ISSUE THREAD

**Issue by sunfuze** [FIRHQ/flow.ci#90]
我们线上现在大部分都更新了node版本到v6，什么时候回支持呢？

**Comment by gy2006** [comment]
感谢关注，现在支持Node v6的版本了
<img width="489" alt="screen shot 2016-11-17 at 4 24 55 pm" src="https://cloud.githubusercontent.com/assets/23307997/20381610/1dec0dc0-ace3-11e6-83b4-dc9fcc7ad599.png">

**Comment by trawor** [comment]
后端还在测试 应该今天就可以上线

sunfuze notifications@github.com于2016年11月17日星期四 15:05写道：
