### ISSUE TITLE
项目编译成功后自动发的邮件中commit跳转不正确

### ISSUE THREAD

**Issue by urmyfaith** [FIRHQ/flow.ci#92]
项目编译成功后自动发的邮件中commit跳转不正确：

如图：

![](http://ww4.sinaimg.cn/large/006tNbRwgw1f9zkb26q5gj30oc0eb75h.jpg)

点击b89af0a2e1ad0  跳转到coding

提示commit不存在。

![](http://ww2.sinaimg.cn/large/006tNbRwgw1f9zk88zezcj30pr06wt91.jpg)

其实commit是存在的，这个commit的全部是：

149d84910fae17d7dce87ae0d91b89af0a2e1ad0

只是因为你们取了后面的一部分，b89af0a2e1ad0

导致跳转不正确。

![](http://ww1.sinaimg.cn/large/006tNbRwgw1f9zk9q3fb4j30si0cuq51.jpg)

**Comment by gy2006** [comment]
此问题已修复，感谢反馈~
