### ISSUE TITLE
现在不支持Gitlab项目了？ 为什么 create project里没看到Gitlab选项了？

### ISSUE THREAD

**Issue by yaojialyu** [FIRHQ/flow.ci#93]

**Comment by gy2006** [comment]
现在 Gitlab 还有一些问题需要修复，很快就会上线的

**Comment by yaojialyu** [comment]
@yang-guo-2016  好的，感谢回复。 
麻烦上线时 close 该issue，以便可以及时知晓。谢谢。

**Comment by playmyswift** [comment]
..... 大问题

**Comment by ByronWalden** [comment]
me too，the same requirement.

**Comment by gy2006** [comment]
@lvyaojia @jiakeqi @ByronWalden 已经恢复GitLab的支持，需要https flow.ci才可以自动添加deploy key & webhook到项目中，否则需要手工添加

**Comment by yaojialyu** [comment]
@yang-guo-2016  感谢。
另一个问题， 为什么加入gitlab地址和token后，只能看到User名下的项目，而Organization里的项目都没有，Sync 了也没有用。

**Comment by gy2006** [comment]
@lvyaojia 已经支持Org的项目了，昨天晚上刚刚上线的

**Comment by blackchena** [comment]
“这些项目您没有创建权限，请联系项目管理员” 关于gitlab 权限问题我需要 gitlab 的什么成员身份呢？
